name: System-level tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]  # all branches, not just main (useful for train of PRs)

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run system-level tests
      run: |
        test/docker-testing.sh
